#!/usr/bin/env python3
"""Build a Hermes-native deployment of the J-Space Cognition Suite from a clean upstream checkout.

Why: Hermes Agent treats only `references/`, `templates/`, `assets/`, `scripts/`, `examples/`
as skill support directories (agent/skill_utils.SKILL_SUPPORT_DIRS). Upstream ships its modules
under `modules/`, so official Hermes installers drop all 13 module files, and `skill_view`
linked-files never lists them. Also, Hermes indexes skill descriptions at 60 chars
(SKILL_PROMPT_DESC_LIMIT), so the long upstream description loses its routing signal.

This script (idempotent, stdlib-only) produces `hermes/out/j-space/`:
  - SKILL.md                    upstream entry + Hermes-ready frontmatter (<=60-char description,
                                version/author/license/platforms/metadata.hermes), a
                                `## When to Use` counter-trigger section, and commands using
                                `${HERMES_SKILL_DIR}` (Hermes substitutes it at load time).
  - references/                 all upstream modules/ (13) + references/ (7), links rewritten
                                (`modules/X` -> `references/X`, `../references/X` -> `X`).
  - scripts/                    upstream scripts verbatim + verify_suite_hermes.py
  - LICENSE, CITATION.cff, THIRD_PARTY_NOTICES.md

Never edits upstream files. Never touches ~/.hermes. Deploy (symlink) is done by sync.sh.

Usage: python3 hermes/build_hermes_skill.py [--repo-root DIR]
Prints `BUILT <n> files, upstream <sha>` (machine-readable) or exits non-zero on failure.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
UPSTREAM = REPO / "j-space"
OUT = REPO / "hermes" / "out" / "j-space"

DESCRIPTION = (
    "Reasoning workspace: ledger, gates, ship checks. Long tasks."
)  # <=60 chars, ends with period, trigger-first

FRONTMATTER_EXTRA = """version: {version}
author: Tiger3807861189 (Upstream), Hermes Agent (adaptation)
license: Apache-2.0
platforms: [linux, macos, windows]
required_commands: [python3]
metadata:
  hermes:
    tags: [reasoning, workspace, long-horizon, verification, ledger]
    requires_toolsets: [terminal]
"""

# Inserted right after the frontmatter, before the upstream body (which starts with # J-Space).
WHEN_TO_USE = """## When to Use

Load for work that needs durable state: multi-step or multi-file tasks, long agentic
runs, holding a goal through mechanical work, calibrated confidence, or delivery gates.
Continue to `The gate` below for the pass level.

Do not load for quick recall, formatting, or answers you can check in one glance — the
fast pass needs no machinery. If you loaded this skill, start with the premise section.

## Hermes Notes

- Invoke the controller through the `terminal` tool (Python 3.10+):
  `<python-command> ${HERMES_SKILL_DIR}/scripts/jspace.py ...` — Hermes substitutes
  `${HERMES_SKILL_DIR}` with this skill's absolute path at load time.
- Keep the ledger with the task, not this directory: pass `--root TASK_DIRECTORY` or
  set the terminal working directory to the task folder (default working directory is
  the session cwd, which wanders; `.jspace/` files have been seen in `$HOME`).
- Hermes ships its own `todo` tool and verification guidance — use them alongside. The
  ledger is the durable cross-turn record; `todo` is the UI-visible surface.
- This skill directory is generated by `hermes/build_hermes_skill.py` and kept in sync by
  `hermes/sync.sh` (cron). Do not hand-edit; edits are overwritten on the next build.
"""


def read_text(p: Path) -> str:
    return p.read_text(encoding="utf-8")


def write_text(p: Path, s: str) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8")


def rewrite_links(text: str) -> str:
    """Adapt upstream relative links to the merged references/ layout.

    Order matters: ``../modules/`` and ``../references/`` (same-directory now, so the
    prefix is dropped) MUST be handled before the generic ``modules/`` -> ``references/``
    rewrite, or they become stale ``../references/`` links (observed 2026-09-21)."""
    text = text.replace("../modules/", "")
    text = text.replace("../references/", "")
    text = text.replace("/modules/", "/references/")   # path-in-code occurrences
    text = re.sub(r"(?<![\w.-])modules/", "references/", text)  # bare `modules/capacity.md`
    text = text.replace("<skill-root>", "${HERMES_SKILL_DIR}")
    return text


def generate_verify_hermes(module_names: list[str], ref_names: list[str]) -> str:
    """Render scripts/verify_suite_hermes.py — verifier for the generated Hermes layout.

    Checks the things the upstream verifier cannot check in this layout: frontmatter
    completeness (Hermes keys), 60-char description budget, the merged references/
    manifest, rewritten links (no stale modules/ or ../references/), and script presence.
    """
    modules = ", ".join(repr(m) for m in module_names)
    refs = ", ".join(repr(r) for r in ref_names)
    return f'''#!/usr/bin/env python3
"""verify_suite_hermes — integrity check for the generated Hermes layout (auto-generated).

Checks (all findings fail non-zero):
  1. SKILL.md frontmatter: name=j-space, description <= 60 chars, Hermes metadata present.
  2. references/ holds exactly the upstream modules + references (merged manifest).
  3. No stale upstream link forms anywhere in SKILL.md or references/.
  4. Controller scripts present.
Exit 0 clean, 1 with findings. Standard library only.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULES = [{modules}]
REFERENCES = [{refs}]
SKILL_MD = ROOT / "SKILL.md"


def main() -> int:
    findings: list[str] = []

    # 1. frontmatter
    if not SKILL_MD.exists():
        findings.append(f"missing {{SKILL_MD.name}}")
        return 1
    text = SKILL_MD.read_text(encoding="utf-8")
    if not text.startswith("---"):
        findings.append("SKILL.md does not start with ---")
    m = re.search(r'^description:\\s*"(.+)"', text, re.M)
    if not m:
        findings.append("description missing")
    elif len(m.group(1)) > 60:
        findings.append(f"description is {{len(m.group(1))}} chars (budget 60)")
    for key in ("version:", "author:", "license:", "platforms:", "required_commands:",
                "metadata:", "tags:", "requires_toolsets:"):
        if key not in text:
            findings.append(f"frontmatter missing {{key}}")

    # 2. merged manifest
    want = sorted(set(MODULES) | set(REFERENCES))
    have = sorted(p.stem for p in (ROOT / "references").glob("*.md"))
    if have != want:
        missing = sorted(set(want) - set(have)); extra = sorted(set(have) - set(want))
        if missing: findings.append(f"references missing: {{missing}}")
        if extra: findings.append(f"references extra: {{extra}}")

    # 3. stale link forms
    stale = []
    for p in [SKILL_MD, *sorted((ROOT / "references").glob("*.md"))]:
        t = p.read_text(encoding="utf-8")
        for bad in ("modules/", "../references/", "<skill-root>"):
            if bad in t:
                stale.append(f"{{p.name}}: '{{bad}}'")
    if stale:
        findings.append("stale links: " + "; ".join(stale))

    # 4. scripts
    for s in ("jspace.py", "control.py", "host_bridge.py", "verify_suite.py"):
        if not (ROOT / "scripts" / s).exists():
            findings.append(f"missing scripts/{{s}}")

    if findings:
        print("verify_suite_hermes: " + str(len(findings)) + " finding(s)")
        for f in findings:
            print("  x " + f)
        return 1
    print(f"verify_suite_hermes: clean — {{len(MODULES)}} modules, {{len(REFERENCES)}} references, links rewritten.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def build_version() -> str:
    """Semantic version = upstream tag (stable across our adaptation commits)."""
    import subprocess
    for ref in ("origin/main", "HEAD"):
        try:
            return subprocess.run(
                ["git", "-C", str(REPO), "describe", "--tags", "--always", ref],
                capture_output=True, text=True, check=True).stdout.strip()
        except Exception:
            continue
    return "unknown"


def sha256_file(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()[:12]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", default=str(REPO))
    args = ap.parse_args()
    repo = Path(args.repo_root)
    upstream = repo / "j-space"
    out = repo / "hermes" / "out" / "j-space"
    if not upstream.is_dir():
        print(f"ERROR: upstream dir not found: {upstream}", file=sys.stderr)
        return 1

    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    # --- SKILL.md --------------------------------------------------------
    skill_md = read_text(upstream / "SKILL.md")
    # Replace upstream frontmatter (name + description only) with Hermes-ready one.
    fm_start = skill_md.index("---\n") + 4
    fm_end = skill_md.index("\n---\n", fm_start)
    body = skill_md[fm_end + 5:]
    version = build_version()
    fm = (
        "---\n"
        "name: j-space\n"
        f"description: \"{DESCRIPTION}\"\n"
        f"{FRONTMATTER_EXTRA.format(version=version)}"
        "---\n"
    )
    new_skill = fm + "\n" + WHEN_TO_USE + "\n" + rewrite_links(body)
    write_text(out / "SKILL.md", new_skill)

    # --- references/: modules + references, links rewritten ---------------
    n_files = 1
    for src_dir in ("modules", "references"):
        for f in (upstream / src_dir).glob("*.md"):
            write_text(out / "references" / f.name, rewrite_links(read_text(f)))
            n_files += 1

    # --- scripts/ verbatim + hermes variant of the verifier ---------------
    (out / "scripts").mkdir(parents=True, exist_ok=True)
    for f in (upstream / "scripts").glob("*"):
        if f.is_file():
            shutil.copy2(f, out / "scripts" / f.name)
            n_files += 1
    # verify_suite_hermes.py: independent verifier for the generated (Hermes) layout.
    module_names = sorted(f.stem for f in (upstream / "modules").glob("*.md"))
    ref_names = sorted(f.stem for f in (upstream / "references").glob("*.md"))
    write_text(out / "scripts" / "verify_suite_hermes.py", generate_verify_hermes(module_names, ref_names))
    n_files += 1

    # --- legal files -------------------------------------------------------
    for name in ("LICENSE", "CITATION.cff", "THIRD_PARTY_NOTICES.md"):
        if (upstream.parent / name).exists():
            shutil.copy2(upstream.parent / name, out / name)
            n_files += 1

    # --- build meta ---------------------------------------------------------
    meta = {
        "upstream_commit": subprocess_sha(repo),
        "build_version": version,
        "files": n_files,
        "description_len": len(DESCRIPTION),
    }
    write_text(out / ".build-meta.json", json.dumps(meta, indent=2) + "\n")

    print(f"BUILT {n_files} files, upstream {meta['upstream_commit']}")
    return 0


def subprocess_sha(repo: Path) -> str:
    import subprocess
    try:
        return subprocess.run(["git", "-C", str(repo), "rev-parse", "--short", "HEAD"],
                              capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


if __name__ == "__main__":
    sys.exit(main())
